//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetmvc_LoginSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [DisplayName("帳號")]
        [Required(ErrorMessage = "請輸入帳號")]
        [StringLength(30,MinimumLength = 6, ErrorMessage = "此帳號長度需介於6-30字元")]
        public string Account { get; set; }

        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        public string Salt { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "請輸入帳號")]
        [StringLength(20, ErrorMessage = "姓名長度最多20字元")]
        public string Name { get; set; }

        [DisplayName("電子郵件")]
        [Required(ErrorMessage = "請輸入Email")]
        [StringLength(200, ErrorMessage = "Email長度最多200字元")]
        [EmailAddress(ErrorMessage = "這不是Email格式")]
        public string Email { get; set; }

        public string AuthCode { get; set; }
    }
}
